### ISSUE TITLE
Provide more information on IPv6

### ISSUE THREAD

**Issue by DutchEllie** [scaleway/docs-content#265]
Hello, 

If it's okay, I'd like to make a suggestion for the documentation. If that is not appreciated, do not hesitate to just tell me where or how I can make a suggestion and to delete my issue.

I have been a long time customer of Scaleway Dedibox and recently decided to seriously try out Scaleway Elements. I have found the documention on Dedibox to always be quite good, at least enough to get stuff working. I have been trying to see if Elements has such good support for IPv6 as well and I have to say, I am slightly disappointed in the documentation. Even IPv4 is barely mentioned at all. I'd love to see more on how IPv6 routing happens on the Elements network, since that's a part that I am particularly interested in.

As a little background, this is what I have been running into:
I have been running a VPN server with full IPv6 support for a while on my Dedibox machine. My VPN clients are given a private IPv4 address and the IPv4 traffic is NATed through the server, while the clients also receive a fully public IPv6 address from my given /56 range there and that is also forwarded right through my server. I'd love to see if I can do something similar with my /64 address on Elements, but I haven't been able to get it working. 

For this to work, I need a little more information on how IPv6 is even routed on the Elements network and I cannot be the only one if I am honest. A little more background would be appreciated. The only information I have ever been able to find was [this blog post](https://blog.scaleway.com/ipv6-the-future-proof-internet-protocol/) on how you have been rolling it out now. That doesn't seem like the best kind of documentation

**Comment by ofranc** [comment]
Hello @DutchEllie ! Thanks for your feedback and your suggestion it's always appreciated. We love getting comments from our users, especially when they have been with us for a long time 😉. To be completely honest, the IPv4 & IPv6 matter is a bit tricky indeed. As of today, when you launch your Elements Instance, it has a floating IPv6 address which means that if you reboot your Instance for whatever reasons, you'll "lose" that IP address. As a result, configuring routes won't work the way you want it to at the moment. However, our teams are working relentlessly so that IPv4 and IPv6 can be configured the same way on all Elements Instances (eg: being able to attach/detach an IP address smoothly). It's on our 2022 Roadmap. If you wanna keep up the discussion, do not hesitate to shoot me an email at ofranc@scaleway.com. Have a great day!
