### ISSUE TITLE
🐞 Documentation Bug: Multi-AZ support

### ISSUE THREAD

**Issue by amit-tewari** [scaleway/docs-content#601]
### Link to the documentation page or resource

https://www.scaleway.com/en/docs/faq/kubernetes#what-is-scaleway-kubernetes-kapsule

### Describe the bug

https://blog.scaleway.com/multi-az-building-the-next-step-for-infrastructure-resiliency/ announced introduction of Multi-AZ in Paris. This mentions
`
In a multi-AZ scenario, we achieve enhanced availability and data durability by distributing the workload into separate geographical zones that are at significant distance from each other. Increasing your infrastructure resilience to a level that would be unreachable with a single data center.
`

The documentation page about Kubernetes says
`
Currently it is available in our Paris (France), Amsterdam (Netherlands) and Warsaw (Poland) Availability Zones and supports at least the latest version of the last 3 major Kubernetes releases.
`

but it is not clear if
- Kubernetes worker nodes can run in all 3 Paris zones or not?
- Block storage is replicated across the zones or not?
- VPC 
- What services are already utilizing Multi-AZ capabilities, and how?

Also, I am not able to find any reference in documentation/ FAQ as how Multi-AZ can help higher availability for workloads or block/ object storage storage.

### Additional context

Being able to run Kubernetes worker nodes in multiple AZs helps us with graceful degradation of services should there the problems that affect one full zone. Also, having block/ object storage durability across two zones is another major improvement.

**Comment by RoRoJ** [comment]
Hi @amit-tewari 

Currently Kubernetes Kapsule worker nodes can only run in one AZ per cluster. Block storage is not replicated across zones, and VPC is not yet available. Watch this space because we are working on all of these things! Our documentation is updated whenever new features like this become available. With [Kubernetes Kosmos](https://www.scaleway.com/en/docs/compute/kubernetes/how-to/create-kosmos-cluster/) however, you can create a cluster and add pools hosted on other cloud providers or other Scaleway AZs.

Keep an eye on our [private betas](https://www.scaleway.com/en/betas/) page to see when we are developing new features, and request early access. You might also be interested in the k8s channel in our [Slack community](https://www.scaleway.com/en/docs/tutorials/scaleway-slack-community/). Check out [Object Storage](https://www.scaleway.com/en/object-storage/) which is a product currently offering a multi-AZ configuration.
