### ISSUE TITLE
👩‍💻 Documentation Request: security groups do not apply to Virtual networks

### ISSUE THREAD

**Issue by Timost** [scaleway/docs-content#864]
### Summary

Following discussion on [slack](https://scaleway-community.slack.com/archives/C01NTFET64D/p1663590198814999), it appears security groups do not apply to traffic incoming from private network.

I think this should be mentioned in the docs:
- https://www.scaleway.com/en/docs/compute/instances/how-to/use-security-groups
- https://www.scaleway.com/en/docs/network/vpc/how-to/configure-instances-public-gw/

### Why is it needed?

I expected the security groups to apply to all traffic **including** from private network.
As a firewall on a VM would work.

Discussing with colleagues, I'm probably not the only one with this expectation.

### Want to write this documentation yourself?

Yes

**Comment by RoRoJ** [comment]
Hi, thanks for bringing this to our attention. We will update the existing doc to point this out. Since this is a modification of existing doc rather than a new tutorial that meets the criteria for a [contribution reward](https://www.scaleway.com/en/docs/contribute/#do-i-get-a-reward-if-i-participate), we will take care of the modification ourselves. Thanks again!
